- name: Setup the instance on GCE
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create storage disk
      gce_pd:
        disk_type: pd-ssd
        zone: "{{ zone }}"
        project_id: "{{ project_id }}"
        size_gb: "{{ size_gb }}"
        image: "{{ image_name }}"
        name: "{{ machine }}-ci-boot"
        state: present
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
    - name: Create the instance
      gce:
        disks:
          - name: "{{ machine }}-ci-boot"
            mode: READ_WRITE
        instance_names: "{{ machine }}-ci"
        machine_type: n1-standard-64
        service_account_email: "{{ service_account_email }}"
        service_account_permissions:
          - userinfo-email
          - storage-ro
          - logging-write
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        zone: "{{ zone }}"
      register: gce
    - name: Wait for SSH to come up
      wait_for: host={{ gce.instance_data[0].public_ip }}
                port=22
                timeout=60
    - name: Add host to groupname
      add_host: hostname={{ gce.instance_data[0].public_ip }}
                groupname=instances


- name: Prepare the daemon binary
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Build the daemon binary
      shell: ./pants binary ci/continuous_integration:daemon
      args:
        chdir: ../
        executable: /bin/bash
    # We expect GOMA_DIR or goma to be at the default location, ~/goma.
    - name: Update the local goma
      shell: python goma_ctl.py update
      args:
        chdir: "{{goma_dir}}"
        executable: /bin/bash


- name: Setup git account
  hosts: instances
  connection: ssh
  become: true
  become_user: clusterfuzz
  tasks:
    # TODO(tanin): Get gitcookies for the service account.
    # The cookie is generated by going to chromium.googlesource.com and clicking
    # on 'Generate new password'.
    - name: Copy ~/.gitcookies
      copy:
        src: "{{gitcookies_path}}"
        dest: ~/.gitcookies
        force: yes
        group: clusterfuzz
        owner: clusterfuzz
        mode: 0600
    - name: Set git cookies
      shell: git config --global http.cookiefile ~/.gitcookies


- name: Setup python-daemon (runit service, folder, log folder, and service)
  hosts: instances
  connection: ssh
  become: true
  vars:
    - files:
        - {'src': 'python_daemon/run', 'dest': '/etc/sv/python-daemon/run', 'recurse': 'no'}
        - {'src': 'python_daemon/log_run', 'dest': '/etc/sv/python-daemon/log/run', 'recurse': 'no'}
        - {'src': '../dist/daemon.pex', 'dest': '/python-daemon', 'recurse': 'no'}
        - {'src': "{{goma_dir}}", 'dest': '/home/clusterfuzz', 'recurse': 'yes'}
  tasks:
    - command: "sv stop python-daemon"
      ignore_errors: yes
    - name: Remove the env dir
      file:
        path: /python-daemon-data/env
        state: absent
    - name: Create important directories
      file: path="{{item}}"
            state=directory
            owner=clusterfuzz
            group=clusterfuzz
            mode='u=rwx,g=rwx,o=rwx'
      with_items:
        - '/python-daemon'
        - '/python-daemon-data'
        - '/python-daemon-data/env'
        - '/etc/sv/python-daemon'
        - '/etc/sv/python-daemon/log'
        - '/var/log/python-daemon'
        - '/home/clusterfuzz/.clusterfuzz'
    - name: Set environment variables through the env dir
      copy: dest="/python-daemon-data/env/{{item.key}}"
            force=yes
            content="{{item.value}}"
            owner=clusterfuzz
            group=clusterfuzz
            mode='u=rwx,g=rwx,o=rwx'
      with_items:
        # Set the release type
        - {'key': 'RELEASE', 'value': "{{release}}"}
        # Set the project id for sending CI logs
        - {'key': 'PROJECT_ID', 'value': "{{project_id}}"}
        # Disable Python optimization because speed is not important
        - {'key': 'PYTHONUNBUFFERED', 'value': '1'}
        - {'key': 'PYTHONDONTWRITEBYTECODE', 'value': '1'}
    - name: Sync important files
      synchronize: src={{item.src}}
                   dest={{item.dest}}
                   mode=push
                   recursive=yes
      with_items: "{{files}}"
    - name: Set appropriate permissions of important files
      file: src={{item.src}}
            dest={{item.dest}}
            owner=clusterfuzz
            group=clusterfuzz
            mode='u=rwx,g=rwx,o=rwx'
            recurse={{item.recurse}}
      with_items: "{{files}}"
    - name: Suppress Goma from auto update
      copy:
        content: ""
        dest: "/home/clusterfuzz/goma/no_auto_update"
        force: no
        group: clusterfuzz
        owner: clusterfuzz
        mode: 0666
    - name: Deploy the release candidate
      copy:
        src: '/google/data/ro/teams/clusterfuzz-tools/releases/clusterfuzz-rc'
        dest: '/python-daemon-data/clusterfuzz'
        force: true
        owner: root
        group: root
        mode:  'u=rwx,g=rwx,o=rwx'
      when: release == "release-candidate"
    - name: Deploy the release
      copy:
        src: '/google/data/ro/teams/clusterfuzz-tools/releases/clusterfuzz'
        dest: '/python-daemon-data/clusterfuzz'
        force: true
        owner: root
        group: root
        mode:  'u=rwx,g=rwx,o=rwx'
      when: release == "release"
    - name: Make the symlink of the service directory
      file:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        state: link
        mode: 'u=rwx,g=rwx,o=rwx'
      with_items:
        - { src: '/etc/sv/python-daemon', dest: '/etc/service/python-daemon' }
    - name: Restarting the daemon.
      shell: "sv restart python-daemon"
      retries: 10
      delay: 1
      register: restart_result
      until: restart_result.rc == 0
