- name: Setup the instance on GCE
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create storage disk
      gce_pd:
        disk_type: pd-ssd
        zone: "us-central1-f"
        project_id: "981641712411"
        size_gb: 100
        image: ubuntu-1404
        name: "ci-test-boot"
        state: present
        service_account_email: "ci-test-tanin@clusterfuzz-tools.iam.gserviceaccount.com"
        credentials_file: "clusterfuzz-tools-ci-credentials.json"
    - name: Create the instance
      gce:
        disks:
          - name: "ci-test-boot"
            mode: READ_WRITE
        instance_names: continuous-integration-test
        machine_type: n1-standard-32
        service_account_email: "ci-test-tanin@clusterfuzz-tools.iam.gserviceaccount.com"
        credentials_file: "clusterfuzz-tools-ci-credentials.json"
        project_id: "981641712411"
        zone: "us-central1-f"
      register: gce
    - name: Wait for SSH to come up
      wait_for: host={{ gce.instance_data[0].public_ip }}
                port=22
                timeout=60
    - name: Add host to groupname
      add_host: hostname={{ gce.instance_data[0].public_ip }}
                groupname=continuous-integration-instances
- name: Configure users and dependencies
  hosts: continuous-integration-instances
  connection: ssh
  become: true
  tasks:
    - group:
        name: clusterfuzz
        state: present
    - name: Allow clusterfuzz group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%clusterfuzz'
        line: '%clusterfuzz ALL=(ALL) NOPASSWD: ALL'
    - user:
        name: clusterfuzz
        state: present
        groups: clusterfuzz
        shell: /bin/bash
    - apt:
        update_cache: yes
    - apt: name={{item}} state=latest
      with_items:
        - python
        - python-pip
        - python-dev
        - runit
        - git
        - pkg-config
        - blackbox
    - name: Upgrade PIP
      pip: name={{item}} state=latest
      with_items:
        - pip
        - wheel
        - setuptools
        - oauth2client
        - virtualenv
        - httplib2
        - pyyaml
- name: Setup python-daemon (runit service, folder, log folder, and service)
  hosts: continuous-integration-instances
  connection: ssh
  become: true
  tasks:
    - file: path="{{item}}"
            state=directory
            owner=clusterfuzz
            group=clusterfuzz
            mode='u=rwx,g=rx,o=rx'
      with_items:
        - '/python-daemon'
    - file: path="{{item}}"
            state=directory
            owner=root
            group=root
            mode='u=rwx,g=rwx,o=rwx'
      with_items:
        - '/etc/sv/python-daemon'
        - '/etc/sv/python-daemon/log'
        - '/var/log/python-daemon'
        - '/home/clusterfuzz/.clusterfuzz'
    - copy: src={{item.src}}
            dest={{item.dest}}
            force=true
            owner=root
            group=root
            mode='u=rwx,g=rwx,o=rwx'
      with_items:
        - {'src': 'python_daemon/run', 'dest': '/etc/sv/python-daemon/run'}
        - {'src': 'python_daemon/log_run', 'dest': '/etc/sv/python-daemon/log/run'}
        - {'src': 'continuous_integration/ci', 'dest': '/python-daemon'}
        - {'src': 'clusterfuzz-tools-ci-credentials.json', 'dest': '/python-daemon/service-account-credentials.json'}
        - {'src': '/auto/FuzzInfrastructure/clusterfuzz-tools/goma', 'dest': '/home/clusterfuzz'}
    - file:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        state: link
        mode: 'u=rwx,g=rwx,o=rwx'
      with_items:
        - { src: '/etc/sv/python-daemon', dest: '/etc/service/python-daemon' }
    - shell: "sv restart python-daemon"
